In [1]:
# Mounting the drive

from google.colab import drive

drive.mount('/content/drive')

print("Drive successfully mounted")

Mounted at /content/drive
Drive successfully mounted

In [2]:
import pandas as pd
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity

This is one of the most popular similarity algorithms.

It compares two vectors.

In [3]:
feature_path = "/content/drive/MyDrive/AI_Healthcare_Diagnosis_system/feature_dataset.xlsx"

df = pd.read_excel(feature_path)

df.head()
df.shape

(134, 402)

In [4]:
disease = df['Disease']

features = df.drop("Disease", axis=1)

In [5]:
disease

0      UMLS:C0001175_acquired immuno-deficiency syndr...
1                           UMLS:C0001418_adenocarcinoma
2                                 UMLS:C0001511_adhesion
3           UMLS:C0001973_chronic alcoholic intoxication
4                      UMLS:C0002395_Alzheimer's disease
                             ...
129                                  UMLS:C1258215_ileus
130                               UMLS:C1456784_paranoia
131                         UMLS:C1510475_diverticulosis
132                    UMLS:C1565489_insufficiency renal
133                              UMLS:C1623038_cirrhosis
Name: Disease, Length: 134, dtype: object

In [7]:
features

,UMLS:C0000727_abdomen acute,UMLS:C0000731_distended abdomen,UMLS:C0000737_pain abdominal,UMLS:C0002416_ambidexterity,UMLS:C0002962_angina pectoris,UMLS:C0003123_anorexia,UMLS:C0003126_anosmia,UMLS:C0003862_arthralgia,UMLS:C0003962_ascites,UMLS:C0004093_asthenia,...,UMLS:C1305739_presence of q wave,UMLS:C1313921_urinoma,UMLS:C1321756_achalasia,UMLS:C1384489_scratch marks,UMLS:C1384606_dyspareunia,UMLS:C1405524_proteinemia,UMLS:C1444773_throbbing sensation quality,UMLS:C1511606_cystic lesion,UMLS:C1513183_metastatic lesion,UMLS:C1517205_flare
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
130,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
131,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
132,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
133,0,1,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
# Display all sysmpotoms
symptom_list = list(features.columns)

print("Total Symptoms:", len(symptom_list))

Total Symptoms: 401

In [9]:
user_vector = np.zeros(len(symptom_list))

In [21]:
# Manually Testing if user Input given
selected_symptoms = [
    "UMLS:C0015967_fever",
    "UMLS:C0010200_cough",
    "UMLS:C0042963_vomiting",
    "UMLS:C0018681_headache",
    "UMLS:C0085593_chill"
]

In [22]:
# Converting symptomps into vector format
for symptom in selected_symptoms:

    if symptom in symptom_list:

        index = symptom_list.index(symptom)

        user_vector[index] = 1

In [23]:
print(user_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [24]:
# Calculating Similarity

similarity_scores = cosine_similarity(
    [user_vector],
    features
)
# compares one user vector against all 134 disease vectors.

In [25]:
print(similarity_scores.shape)

(1, 134)

In [26]:
# Flatten the Scores
similarity_scores = similarity_scores.flatten()

print(similarity_scores)

[0.35856858 0.         0.12403473 0.         0.21693046 0.1
 0.13483997 0.         0.         0.         0.1490712  0.3354102
 0.         0.         0.         0.21693046 0.32539569 0.
 0.11952286 0.23094011 0.         0.11547005 0.23904572 0.10846523
 0.         0.13483997 0.3721042  0.1        0.         0.25819889
 0.         0.23094011 0.12909944 0.         0.         0.11952286
 0.11547005 0.2        0.13483997 0.1118034  0.         0.10846523
 0.34641016 0.12909944 0.13483997 0.         0.         0.
 0.         0.16903085 0.         0.1118034  0.38729833 0.
 0.26967994 0.10540926 0.         0.23094011 0.15811388 0.
 0.         0.         0.         0.         0.         0.09759001
 0.         0.38729833 0.29277002 0.         0.18257419 0.
 0.28603878 0.12909944 0.14142136 0.2236068  0.12403473 0.
 0.2981424  0.11952286 0.         0.         0.1118034  0.24806947
 0.         0.12403473 0.         0.12909944 0.         0.1490712
 0.         0.         0.12909944 0.         0.         0.30779351
 0.2236068  0.21081851 0.15811388 0.         0.         0.
 0.         0.42426407 0.         0.         0.23904572 0.
 0.18650096 0.13483997 0.1490712  0.28284271 0.16903085 0.12909944
 0.         0.         0.13483997 0.         0.3380617  0.
 0.11547005 0.         0.         0.         0.21693046 0.
 0.         0.         0.         0.         0.         0.
 0.         0.        ]

In [27]:
# FInding top 3 Diseases

top3 = np.argsort(similarity_scores)[-3:][::-1]

print(top3)

[103  67  52]

In [28]:
# Display the prediction
for i in top3:
    print("Disease :", disease.iloc[i])
    print("Similarity :", round(similarity_scores[i] * 100, 2), "%")
    print("-" * 50)

Disease : UMLS:C0034186_pyelonephritis
Similarity : 42.43 %
--------------------------------------------------
Disease : UMLS:C0021311_infection
Similarity : 38.73 %
--------------------------------------------------
Disease : UMLS:C0019158_hepatitis
Similarity : 38.73 %
--------------------------------------------------

In [29]:
print(similarity_scores.shape)

(134,)

In [30]:
# Displaying Disease name more user friendly
def clean_disease_name(name):
    # Split multiple disease names
    name = name.split("^")[0]

    # Remove UMLS code
    if "_" in name:
        name = name.split("_", 1)[1]

    return name.title()

In [32]:
diseases_clean = disease.apply(clean_disease_name)

In [33]:
for i in top3:
    print(diseases_clean.iloc[i])

Pyelonephritis
Infection
Hepatitis

In [34]:
# For feature
def clean_symptom(symptom):
    if "_" in symptom:
        symptom = symptom.split("_", 1)[1]

    return symptom.replace("_", " ").title()

In [35]:
clean_symptoms = [clean_symptom(s) for s in symptom_list]

print(clean_symptoms[:10])

['Abdomen Acute', 'Distended Abdomen', 'Pain Abdominal', 'Ambidexterity', 'Angina Pectoris', 'Anorexia', 'Anosmia', 'Arthralgia', 'Ascites', 'Asthenia']