In [14]:
# Mounting the drive

from google.colab import drive

drive.mount('/content/drive')

print("Drive successfully mounted")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Drive successfully mounted

In [15]:
import pandas as pd

file_path = '/content/drive/MyDrive/AI_Healthcare_Diagnosis_system/cleaned_data.xlsx'

df = pd.read_excel(file_path)
df.head(10)

,Disease,Count of Disease Occurrence,Symptom
0,UMLS:C0020538_hypertensive disease,3363,UMLS:C0008031_pain chest
1,UMLS:C0020538_hypertensive disease,3363,UMLS:C0392680_shortness of breath
2,UMLS:C0020538_hypertensive disease,3363,UMLS:C0012833_dizziness
3,UMLS:C0020538_hypertensive disease,3363,UMLS:C0004093_asthenia
4,UMLS:C0020538_hypertensive disease,3363,UMLS:C0085639_fall
5,UMLS:C0020538_hypertensive disease,3363,UMLS:C0039070_syncope
6,UMLS:C0020538_hypertensive disease,3363,UMLS:C0042571_vertigo
7,UMLS:C0020538_hypertensive disease,3363,UMLS:C0038990_sweat^UMLS:C0700590_sweating inc...
8,UMLS:C0020538_hypertensive disease,3363,UMLS:C0030252_palpitation
9,UMLS:C0020538_hypertensive disease,3363,UMLS:C0027497_nausea

In [16]:
# Inspecting one disease
df[df['Disease'] == "UMLS:C0011847_diabetes"]

,Disease,Count of Disease Occurrence,Symptom
12,UMLS:C0011847_diabetes,1421,UMLS:C0032617_polyuria
13,UMLS:C0011847_diabetes,1421,UMLS:C0085602_polydypsia
14,UMLS:C0011847_diabetes,1421,UMLS:C0392680_shortness of breath
15,UMLS:C0011847_diabetes,1421,UMLS:C0008031_pain chest
16,UMLS:C0011847_diabetes,1421,UMLS:C0004093_asthenia
17,UMLS:C0011847_diabetes,1421,UMLS:C0027497_nausea
18,UMLS:C0011847_diabetes,1421,UMLS:C0085619_orthopnea
19,UMLS:C0011847_diabetes,1421,UMLS:C0034642_rale
20,UMLS:C0011847_diabetes,1421,UMLS:C0038990_sweat^UMLS:C0700590_sweating inc...
21,UMLS:C0011847_diabetes,1421,UMLS:C0241526_unresponsiveness
22,UMLS:C0011847_diabetes,1421,UMLS:C0856054_mental status changes
23,UMLS:C0011847_diabetes,1421,UMLS:C0042571_vertigo
24,UMLS:C0011847_diabetes,1421,UMLS:C0042963_vomiting
25,UMLS:C0011847_diabetes,1421,UMLS:C0553668_labored breathing

In [17]:

disease_symp = df.groupby('Disease')['Symptom'].apply(list)

disease_symp.head(10)

Disease
UMLS:C0001175_acquired immuno-deficiency syndrome^UMLS:C0019682_HIV^UMLS:C0019693_hiv infections    [UMLS:C0015967_fever, UMLS:C0028081_night swea...
UMLS:C0001418_adenocarcinoma                                                                        [UMLS:C0577559_mass of body structure, UMLS:C0...
UMLS:C0001511_adhesion                                                                              [UMLS:C0016204_flatulence, UMLS:C0030193_pain,...
UMLS:C0001973_chronic alcoholic intoxication                                                        [UMLS:C0040822_tremor, UMLS:C0233762_hallucina...
UMLS:C0002395_Alzheimer's disease                                                                   [UMLS:C0013132_drool, UMLS:C0085631_agitation,...
UMLS:C0002871_anemia                                                                                [UMLS:C0085593_chill, UMLS:C0744492_guaiac pos...
UMLS:C0002895_sickle cell anemia                                                                    [UMLS:C1135120_breakthrough pain, UMLS:C000460...
UMLS:C0003507_stenosis aortic valve                                                                 [UMLS:C0231807_dyspnea on exertion, UMLS:C0039...
UMLS:C0003537_aphasia                                                                               [UMLS:C0009024_clonus, UMLS:C0231872_egophony,...
UMLS:C0003864_arthritis                                                                             [UMLS:C0030193_pain, UMLS:C0578150_hemodynamic...
Name: Symptom, dtype: object

In [18]:
disease_symp = disease_symp.reset_index()

disease_symp.head(10)

,Disease,Symptom
0,UMLS:C0001175_acquired immuno-deficiency syndr...,"[UMLS:C0015967_fever, UMLS:C0028081_night swea..."
1,UMLS:C0001418_adenocarcinoma,"[UMLS:C0577559_mass of body structure, UMLS:C0..."
2,UMLS:C0001511_adhesion,"[UMLS:C0016204_flatulence, UMLS:C0030193_pain,..."
3,UMLS:C0001973_chronic alcoholic intoxication,"[UMLS:C0040822_tremor, UMLS:C0233762_hallucina..."
4,UMLS:C0002395_Alzheimer's disease,"[UMLS:C0013132_drool, UMLS:C0085631_agitation,..."
5,UMLS:C0002871_anemia,"[UMLS:C0085593_chill, UMLS:C0744492_guaiac pos..."
6,UMLS:C0002895_sickle cell anemia,"[UMLS:C1135120_breakthrough pain, UMLS:C000460..."
7,UMLS:C0003507_stenosis aortic valve,"[UMLS:C0231807_dyspnea on exertion, UMLS:C0039..."
8,UMLS:C0003537_aphasia,"[UMLS:C0009024_clonus, UMLS:C0231872_egophony,..."
9,UMLS:C0003864_arthritis,"[UMLS:C0030193_pain, UMLS:C0578150_hemodynamic..."

In [19]:
# Count the Diseases
print("Number of Disease:", len(disease_symp))

Number of Disease: 134

In [20]:
# Checking one disease symptoms list
disease_symp.iloc[0]

Disease    UMLS:C0001175_acquired immuno-deficiency syndr...
Symptom    [UMLS:C0015967_fever, UMLS:C0028081_night swea...
Name: 0, dtype: object

In [21]:
print("Shape:", disease_symp.shape)

Shape: (134, 2)

In [22]:
# Now we are going to create the feature matrix for the training, extracting the dataset into 1,0 format for all sysmptoms there will be one column associated

all_symptoms = sorted(df['Symptom'].unique())

print("Total Unique Symptoms:", len(all_symptoms))

Total Unique Symptoms: 401

In [24]:
feature_df = pd.DataFrame(0, index = disease_symp.index, columns= all_symptoms)

feature_df.head()

,UMLS:C0000727_abdomen acute,UMLS:C0000731_distended abdomen,UMLS:C0000737_pain abdominal,UMLS:C0002416_ambidexterity,UMLS:C0002962_angina pectoris,UMLS:C0003123_anorexia,UMLS:C0003126_anosmia,UMLS:C0003862_arthralgia,UMLS:C0003962_ascites,UMLS:C0004093_asthenia,...,UMLS:C1305739_presence of q wave,UMLS:C1313921_urinoma,UMLS:C1321756_achalasia,UMLS:C1384489_scratch marks,UMLS:C1384606_dyspareunia,UMLS:C1405524_proteinemia,UMLS:C1444773_throbbing sensation quality,UMLS:C1511606_cystic lesion,UMLS:C1513183_metastatic lesion,UMLS:C1517205_flare
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
for i, symptoms in enumerate(disease_symp["Symptom"]):
    for symptom in symptoms:
        feature_df.loc[i, symptom] = 1

In [26]:
feature_df.insert(0, "Disease", disease_symp["Disease"])

In [30]:
feature_df.head()

,Disease,UMLS:C0000727_abdomen acute,UMLS:C0000731_distended abdomen,UMLS:C0000737_pain abdominal,UMLS:C0002416_ambidexterity,UMLS:C0002962_angina pectoris,UMLS:C0003123_anorexia,UMLS:C0003126_anosmia,UMLS:C0003862_arthralgia,UMLS:C0003962_ascites,...,UMLS:C1305739_presence of q wave,UMLS:C1313921_urinoma,UMLS:C1321756_achalasia,UMLS:C1384489_scratch marks,UMLS:C1384606_dyspareunia,UMLS:C1405524_proteinemia,UMLS:C1444773_throbbing sensation quality,UMLS:C1511606_cystic lesion,UMLS:C1513183_metastatic lesion,UMLS:C1517205_flare
0,UMLS:C0001175_acquired immuno-deficiency syndr...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,UMLS:C0001418_adenocarcinoma,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,UMLS:C0001511_adhesion,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,UMLS:C0001973_chronic alcoholic intoxication,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,UMLS:C0002395_Alzheimer's disease,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
print(feature_df.shape)

(134, 402)

In [38]:
# Saving the Feature matrix file
feature_path = "/content/drive/MyDrive/AI_Healthcare_Diagnosis_system/feature_dataset.xlsx"
feature_df.to_excel(feature_path, index=False)

print("Feature dataset saved successfully!")

Feature dataset saved successfully!

In [37]:
print(feature_df.shape)

(134, 402)